### ISSUE TITLE
Action Mailers :)

### ISSUE THREAD

**Issue by tayb18** [homework-homies/hw-hub#42]
Hey @phlco I was hoping to get  a little bit of help on this action mailer nonsense. It seemed SO greate when I first read through the Action Mailer Basics Ruby doc. But they really set themselves up in an ideal scenario, and I'm not totally sure how to adapt their example to fit my specific data structure. 

I created the gist_email method in the gist_mailer.rb file in the mailers folder.
Now I am trying to call the mailer in the gists_controller.rb file, where the gist is created.
But I can't figure out how to access the students email addresses when I do so.

This is the link to the branch I am currently working out of. Any friendly advice (or non-friendly I guess) is greatly appreciated :) 
https://github.com/homework-homies/hw-hub/tree/gist-action-mailer

**Comment by phlco** [comment]
Let me see if I understand your question. "How do I access all the student email addresses from the GistsController?"

There's some clean up to be done in the "Gists#create" method. 

``` rb
  def create
    @gist = Gist.create(gist_params)
    @students = @gist.cohort.students # no need to assign this to a new variable
    @students.each do |student|
      respond_to do |format|  # take this out. respond_to is probably from scaffolding something
        if @gist.save # you don't need to keep calling this here
          GistMailer.gist_email(student.email).deliver_now
        end
      end
    end 
    redirect_to @gist
  end
```

Taking those things into consideration try it like this:

``` rb
def create
  @gist = Gist.create(gist_params)
    if @gist.save
      @gist.cohort.students.each do |student|
        GistMailer.gist_email(student.email).deliver_now
      end
      redirect_to @gist
    end
  end 
end
```

Now all the above code depends on your `gist_email` method defined in your "GistMailer"

From your code above I'd assume that your "gist_email" method takes an email as a parameter.

But looking at this code: 

``` rb
  def gist_email # you haven't set this method to take any parameters
    @students = Student.all  # This shouldn't be there. 
    @url = 'http://example.com/GIST_LINK_HERE'
   # you can't call .email on the students array. It's an instance method for an individual student.
    mail(to: @students.email, subject: "Attention! A New Gist Has Been Created")
  end
```

Taking those things into consideration, maybe you'd want to try something like:

``` rb
  def gist_email(email)
    @url = 'http://example.com/GIST_LINK_HERE'
    mail(to: email, subject: "Attention! A New Gist Has Been Created")
  end
```

Let me know how that goes.

**Comment by tayb18** [comment]
Oooooook those are some very helpful leads. Let me think on these things and I'll get back to you next time I confuse myself.

Thank you for your help!

**Comment by jessleenyc** [comment]
Resolved!
